# serverless.yml

service: dataretrieval

functions:
  pullFile:
    handler: puller.pullFile
    events:
      - http:
          method: post
          path: pull-file
          cors: true
  pullRecord:
    handler: retriever.pullRecord
    events:
      - http:
          method: post
          path: pull-record
          cors: true
  submitData:
    handler: handler.submitData
    events:
      - http:
          method: post
          path: submit-data
          cors: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  memorySize: 128
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendRawEmail"
        - "ses:SendEmail"
        - "s3:ListBucket"
        - "s3:CreateBucket"
        - "s3:PutBucketPolicy"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: ["*"]